version: "3.8"

services:
  frontend_his:
    image: dockerhiscis/frontend-his:latest
    # depends_on:
    #   - gateway_api
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: service nginx status || exit 1
      interval: 5s
      retries: 2
      start_period: 2s
      timeout: 10s
