version: "3.8"

services:
  gateway_api:
    image: dockerhiscis/gateway_api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Bangkok
    ports:
      - "8888:80"
    networks:
      - api-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
      interval: 5s
      retries: 2
      start_period: 2s
      timeout: 10s

networks:
  api-network:
    external: true
