version: "3.8"

services:
  grafana:
    image: grafana/grafana:8.5.0-51645pre-ubuntu
    ports:
      - "3131:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
    networks:
      - monitor-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  monitor-network:
    external: true
