version: "3.8"

services:
  minio_server:
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=1234
      - MINIO_SERVER_URL=http://localhost:9000
    volumes:
      - minio_data:/data
    networks:
      - minio-network
    ports:
      - "9090:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 2
      start_period: 2s
      timeout: 30s

networks:
  minio-network:
    external: true

volumes:
  minio_data:
    external: true
    name: minio_data
