version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@1234.com
      - PGADMIN_DEFAULT_PASSWORD=Admin123_
      - TZ=Asia/Bangkok
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dbpis-network
      - dbpharmm-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  dbpis-network:
    external: true
  dbpharmm-network:
    external: true

volumes:
  pgadmin_data:
    external: true
    name: pgadmin_data
