version: "3.8"

services:
  pis_api:
    image: dockerhiscis/pharmm_api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=dbpharmm;Port=5432;Database=pharmm;User Id=admin;Password=Admin123_;"
      - "ServerIp=134.209.102.123"
      - TZ=Asia/Bangkok
    ports:
      - "5001:80"
    networks:
      - dbpharmm-network
      - api-network
      - rabbit-network
      - sagamachine-network
      - seq-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
      interval: 5s
      retries: 2
      start_period: 2s
      timeout: 10s

networks:
  api-network:
    external: true
  dbpis-network:
    external: true
  rabbit-network:
    external: true
  sagamachine-network:
    external: true
  seq-network:
    external: true
  minio-network:
    external: true
