version: "3.8"

services:
  postgres-exporter-pharmm:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9188:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:Admin123_@dbpharmm:5432/pharmm?sslmode=disable
    networks:
      - monitor-network
      - dbpharmm-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  monitor-network:
    external: true
  dbpharmm-network:
    external: true
