version: "3.8"

services:
  statemachinedb:
    image: mongo:4.4.6
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - orderstatedb_data:/data/db
    networks:
      - sagadb-network
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      retries: 2
      start_period: 2s
      timeout: 10s

networks:
  sagadb-network:
    external: true

volumes:
  orderstatedb_data:
    external: true
    name: orderstatedb_data
